CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(40) NOT NULL,
                       email VARCHAR(254) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       phone_number VARCHAR(30) NOT NULL UNIQUE,
                       account_status VARCHAR(30) NOT NULL,
                       created_at TIMESTAMP NOT NULL,
                       updated_at TIMESTAMP NOT NULL
);

CREATE TABLE city (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR(200) NOT NULL,
                      state VARCHAR(200) NOT NULL,
                      country VARCHAR(200) NOT NULL
);

CREATE TABLE movie (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title VARCHAR(100) NOT NULL,
                       description VARCHAR(1000) NOT NULL,
                       poster_url VARCHAR(1000) NOT NULL,
                       movie_status VARCHAR(30) NOT NULL,
                       duration_in_minutes INTEGER,
                       release_date DATE
);

CREATE TABLE genre (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE language (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE person (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(250) NOT NULL
);

CREATE TABLE theatre (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(200) NOT NULL,
                         address VARCHAR(300) NOT NULL,
                         city_id BIGINT NOT NULL,
                         CONSTRAINT fk_theatre_city
                             FOREIGN KEY (city_id) REFERENCES city(id)
);

CREATE TABLE screen (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(20) NOT NULL,
                        theatre_id BIGINT NOT NULL,
                        CONSTRAINT fk_screen_theatre
                            FOREIGN KEY (theatre_id) REFERENCES theatre(id)
);

CREATE TABLE seat (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      seat_number VARCHAR(10) NOT NULL,
                      seat_type VARCHAR(30) NOT NULL,
                      screen_id BIGINT NOT NULL,
                      CONSTRAINT fk_seat_screen
                          FOREIGN KEY (screen_id) REFERENCES screen(id),
                      CONSTRAINT uk_seat_screen_number
                          UNIQUE (screen_id, seat_number)
);

CREATE TABLE show (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      movie_id BIGINT NOT NULL,
                      screen_id BIGINT NOT NULL,
                      show_date DATE NOT NULL,
                      ticket_price NUMERIC(10,2) NOT NULL,
                      start_time TIME NOT NULL,
                      end_time TIME NOT NULL,
                      CONSTRAINT fk_show_movie
                          FOREIGN KEY (movie_id) REFERENCES movie(id),
                      CONSTRAINT fk_show_screen
                          FOREIGN KEY (screen_id) REFERENCES screen(id)
);

CREATE TABLE show_seat (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           show_id BIGINT NOT NULL,
                           seat_id BIGINT NOT NULL,
                           seat_status VARCHAR(30) NOT NULL,
                           locked_until TIMESTAMP,
                           CONSTRAINT fk_show_seat_show
                               FOREIGN KEY (show_id) REFERENCES show(id),
                           CONSTRAINT fk_show_seat_seat
                               FOREIGN KEY (seat_id) REFERENCES seat(id),
                           CONSTRAINT uk_show_seat
                               UNIQUE (show_id, seat_id)
);

CREATE TABLE booking (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         user_id BIGINT NOT NULL,
                         show_id BIGINT NOT NULL,
                         booking_status VARCHAR(30) NOT NULL,
                         total_price NUMERIC(12,2) NOT NULL,
                         created_at TIMESTAMP,
                         booked_at TIMESTAMP,
                         cancelled_at TIMESTAMP,
                         CONSTRAINT fk_booking_user
                             FOREIGN KEY (user_id) REFERENCES users(id),
                         CONSTRAINT fk_booking_show
                             FOREIGN KEY (show_id) REFERENCES show(id)
);

CREATE TABLE booking_seat (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              booking_id BIGINT NOT NULL,
                              show_seat_id BIGINT NOT NULL,
                              price NUMERIC(12,2) NOT NULL,
                              CONSTRAINT fk_booking_seat_booking
                                  FOREIGN KEY (booking_id) REFERENCES booking(id),
                              CONSTRAINT fk_booking_seat_show_seat
                                  FOREIGN KEY (show_seat_id) REFERENCES show_seat(id),
                              CONSTRAINT uk_booking_show_seat
                                  UNIQUE (booking_id, show_seat_id)
);

CREATE TABLE payment (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         booking_id BIGINT NOT NULL,
                         payment_status VARCHAR(30) NOT NULL,
                         amount NUMERIC(12,2) NOT NULL,
                         paid_at TIMESTAMP,
                         refunded_at TIMESTAMP,
                         razorpay_order_id VARCHAR(100) NOT NULL UNIQUE,
                         razorpay_payment_id VARCHAR(100) UNIQUE,
                         CONSTRAINT fk_payment_booking
                             FOREIGN KEY (booking_id) REFERENCES booking(id)
);


CREATE TABLE movie_genre (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             movie_id BIGINT NOT NULL,
                             genre_id BIGINT NOT NULL,
                             CONSTRAINT fk_movie_genre_movie
                                 FOREIGN KEY (movie_id) REFERENCES movie(id),
                             CONSTRAINT fk_movie_genre_genre
                                 FOREIGN KEY (genre_id) REFERENCES genre(id),
                             CONSTRAINT uk_movie_genre
                                 UNIQUE (movie_id, genre_id)
);

CREATE TABLE movie_language (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                movie_id BIGINT NOT NULL,
                                language_id BIGINT NOT NULL,
                                CONSTRAINT fk_movie_language_movie
                                    FOREIGN KEY (movie_id) REFERENCES movie(id),
                                CONSTRAINT fk_movie_language_language
                                    FOREIGN KEY (language_id) REFERENCES language(id),
                                CONSTRAINT uk_movie_language
                                    UNIQUE (movie_id, language_id)
);

CREATE TABLE movie_person (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              movie_id BIGINT NOT NULL,
                              person_id BIGINT NOT NULL,
                              role VARCHAR(30) NOT NULL,
                              CONSTRAINT fk_movie_person_movie
                                  FOREIGN KEY (movie_id) REFERENCES movie(id),
                              CONSTRAINT fk_movie_person_person
                                  FOREIGN KEY (person_id) REFERENCES person(id),
                              CONSTRAINT uk_movie_person_role
                                  UNIQUE (movie_id, person_id, role)
);